MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("sysu_train",) # sysu_train, prw_train
  TEST: ("sysu_test", "sysu_query",) # sysu_test, sysu_query, prw_test, prw_query
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 40000)
  MAX_ITER: 45000
  IMS_PER_BATCH: 8
REID:
  USE_REID: True
  OUT_CHANNELS: 2048
  USE_DIFF_FEAT: True
