MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C5"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 2048
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.03125,)
#    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"  # "FPN2MLPFeatureExtractor", "FPNXconv1fcFeatureExtractor"
    NUM_STACKED_CONVS: 1
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("sysu_train",) # sysu_train, prw_train
  TEST: ("sysu_test", "sysu_query",) # sysu_test, sysu_query, prw_test, prw_query
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 40000)
  MAX_ITER: 45000

REID:
  USE_REID: True
  OUT_CHANNELS: 2048
  LOSS_SCALE: 0.7
  USE_DIFF_FEAT: True

